// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: orders-saga-orchestrator.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статусы шага саги
type SagaStatus int32

const (
	SagaStatus_SAGA_STATUS_UNSPECIFIED SagaStatus = 0
	SagaStatus_SAGA_STATUS_PENDING     SagaStatus = 1
	SagaStatus_SAGA_STATUS_COMPLETED   SagaStatus = 2
	SagaStatus_SAGA_STATUS_FAILED      SagaStatus = 3
	SagaStatus_SAGA_STATUS_COMPENSATED SagaStatus = 4
)

// Enum value maps for SagaStatus.
var (
	SagaStatus_name = map[int32]string{
		0: "SAGA_STATUS_UNSPECIFIED",
		1: "SAGA_STATUS_PENDING",
		2: "SAGA_STATUS_COMPLETED",
		3: "SAGA_STATUS_FAILED",
		4: "SAGA_STATUS_COMPENSATED",
	}
	SagaStatus_value = map[string]int32{
		"SAGA_STATUS_UNSPECIFIED": 0,
		"SAGA_STATUS_PENDING":     1,
		"SAGA_STATUS_COMPLETED":   2,
		"SAGA_STATUS_FAILED":      3,
		"SAGA_STATUS_COMPENSATED": 4,
	}
)

func (x SagaStatus) Enum() *SagaStatus {
	p := new(SagaStatus)
	*p = x
	return p
}

func (x SagaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_saga_orchestrator_proto_enumTypes[0].Descriptor()
}

func (SagaStatus) Type() protoreflect.EnumType {
	return &file_orders_saga_orchestrator_proto_enumTypes[0]
}

func (x SagaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaStatus.Descriptor instead.
func (SagaStatus) EnumDescriptor() ([]byte, []int) {
	return file_orders_saga_orchestrator_proto_rawDescGZIP(), []int{0}
}

// Статусы всей саги
type SagaStepStatus int32

const (
	SagaStepStatus_SAGA_STEP_STATUS_UNSPECIFIED SagaStepStatus = 0
	SagaStepStatus_SAGA_STEP_STATUS_COMPLETED   SagaStepStatus = 1
	SagaStepStatus_SAGA_STEP_STATUS_FAILED      SagaStepStatus = 2
)

// Enum value maps for SagaStepStatus.
var (
	SagaStepStatus_name = map[int32]string{
		0: "SAGA_STEP_STATUS_UNSPECIFIED",
		1: "SAGA_STEP_STATUS_COMPLETED",
		2: "SAGA_STEP_STATUS_FAILED",
	}
	SagaStepStatus_value = map[string]int32{
		"SAGA_STEP_STATUS_UNSPECIFIED": 0,
		"SAGA_STEP_STATUS_COMPLETED":   1,
		"SAGA_STEP_STATUS_FAILED":      2,
	}
)

func (x SagaStepStatus) Enum() *SagaStepStatus {
	p := new(SagaStepStatus)
	*p = x
	return p
}

func (x SagaStepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaStepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_saga_orchestrator_proto_enumTypes[1].Descriptor()
}

func (SagaStepStatus) Type() protoreflect.EnumType {
	return &file_orders_saga_orchestrator_proto_enumTypes[1]
}

func (x SagaStepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaStepStatus.Descriptor instead.
func (SagaStepStatus) EnumDescriptor() ([]byte, []int) {
	return file_orders_saga_orchestrator_proto_rawDescGZIP(), []int{1}
}

// Шаг саги
type SagaStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "ivnentory_check" или "payment_check"
	Status        SagaStepStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.orderssagaorchestrator.SagaStepStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaStep) Reset() {
	*x = SagaStep{}
	mi := &file_orders_saga_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaStep) ProtoMessage() {}

func (x *SagaStep) ProtoReflect() protoreflect.Message {
	mi := &file_orders_saga_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaStep.ProtoReflect.Descriptor instead.
func (*SagaStep) Descriptor() ([]byte, []int) {
	return file_orders_saga_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SagaStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SagaStep) GetStatus() SagaStepStatus {
	if x != nil {
		return x.Status
	}
	return SagaStepStatus_SAGA_STEP_STATUS_UNSPECIFIED
}

// Сага для заказа
type OrderSaga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        SagaStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=api.v1.orderssagaorchestrator.SagaStatus" json:"status,omitempty"`
	Steps         []*SagaStep            `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSaga) Reset() {
	*x = OrderSaga{}
	mi := &file_orders_saga_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSaga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSaga) ProtoMessage() {}

func (x *OrderSaga) ProtoReflect() protoreflect.Message {
	mi := &file_orders_saga_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSaga.ProtoReflect.Descriptor instead.
func (*OrderSaga) Descriptor() ([]byte, []int) {
	return file_orders_saga_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *OrderSaga) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderSaga) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderSaga) GetStatus() SagaStatus {
	if x != nil {
		return x.Status
	}
	return SagaStatus_SAGA_STATUS_UNSPECIFIED
}

func (x *OrderSaga) GetSteps() []*SagaStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// Запрос на получение саги по ID заказа
type GetOrderSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderSagaRequest) Reset() {
	*x = GetOrderSagaRequest{}
	mi := &file_orders_saga_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderSagaRequest) ProtoMessage() {}

func (x *GetOrderSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_saga_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderSagaRequest.ProtoReflect.Descriptor instead.
func (*GetOrderSagaRequest) Descriptor() ([]byte, []int) {
	return file_orders_saga_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderSagaRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// Ответ с данными саги
type GetOrderSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          *OrderSaga             `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderSagaResponse) Reset() {
	*x = GetOrderSagaResponse{}
	mi := &file_orders_saga_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderSagaResponse) ProtoMessage() {}

func (x *GetOrderSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_saga_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderSagaResponse.ProtoReflect.Descriptor instead.
func (*GetOrderSagaResponse) Descriptor() ([]byte, []int) {
	return file_orders_saga_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderSagaResponse) GetSaga() *OrderSaga {
	if x != nil {
		return x.Saga
	}
	return nil
}

var File_orders_saga_orchestrator_proto protoreflect.FileDescriptor

const file_orders_saga_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1eorders-saga-orchestrator.proto\x12\x1dapi.v1.orderssagaorchestrator\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n" +
	"\bSagaStep\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12E\n" +
	"\x06status\x18\x02 \x01(\x0e2-.api.v1.orderssagaorchestrator.SagaStepStatusR\x06status\"\xca\x01\n" +
	"\tOrderSaga\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\"\n" +
	"\border_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2).api.v1.orderssagaorchestrator.SagaStatusR\x06status\x12=\n" +
	"\x05steps\x18\x04 \x03(\v2'.api.v1.orderssagaorchestrator.SagaStepR\x05steps\"9\n" +
	"\x13GetOrderSagaRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\"T\n" +
	"\x14GetOrderSagaResponse\x12<\n" +
	"\x04saga\x18\x01 \x01(\v2(.api.v1.orderssagaorchestrator.OrderSagaR\x04saga*\x92\x01\n" +
	"\n" +
	"SagaStatus\x12\x1b\n" +
	"\x17SAGA_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SAGA_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15SAGA_STATUS_COMPLETED\x10\x02\x12\x16\n" +
	"\x12SAGA_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17SAGA_STATUS_COMPENSATED\x10\x04*o\n" +
	"\x0eSagaStepStatus\x12 \n" +
	"\x1cSAGA_STEP_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSAGA_STEP_STATUS_COMPLETED\x10\x01\x12\x1b\n" +
	"\x17SAGA_STEP_STATUS_FAILED\x10\x022\xe2\x02\n" +
	"\x1dOrdersSagaOrchestratorService\x12\xc0\x02\n" +
	"\fGetOrderSaga\x122.api.v1.orderssagaorchestrator.GetOrderSagaRequest\x1a3.api.v1.orderssagaorchestrator.GetOrderSagaResponse\"\xc6\x01\x92A\x9b\x01\n" +
	"\x05sagas\x12(Получение саги заказа\x1ahПолучение информации о саге заказа и её шагах выполнения\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/sagas/orders/{order_id}B\x98\x01\x92A\x84\x01\x12^\n" +
	"\x18Orders Saga Orchestrator\x12;Service for managing order sagas and their completion steps2\x051.0.02\x10application/json:\x10application/jsonZ\x0epkg/api/v1;apib\x06proto3"

var (
	file_orders_saga_orchestrator_proto_rawDescOnce sync.Once
	file_orders_saga_orchestrator_proto_rawDescData []byte
)

func file_orders_saga_orchestrator_proto_rawDescGZIP() []byte {
	file_orders_saga_orchestrator_proto_rawDescOnce.Do(func() {
		file_orders_saga_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_saga_orchestrator_proto_rawDesc), len(file_orders_saga_orchestrator_proto_rawDesc)))
	})
	return file_orders_saga_orchestrator_proto_rawDescData
}

var file_orders_saga_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orders_saga_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orders_saga_orchestrator_proto_goTypes = []any{
	(SagaStatus)(0),              // 0: api.v1.orderssagaorchestrator.SagaStatus
	(SagaStepStatus)(0),          // 1: api.v1.orderssagaorchestrator.SagaStepStatus
	(*SagaStep)(nil),             // 2: api.v1.orderssagaorchestrator.SagaStep
	(*OrderSaga)(nil),            // 3: api.v1.orderssagaorchestrator.OrderSaga
	(*GetOrderSagaRequest)(nil),  // 4: api.v1.orderssagaorchestrator.GetOrderSagaRequest
	(*GetOrderSagaResponse)(nil), // 5: api.v1.orderssagaorchestrator.GetOrderSagaResponse
}
var file_orders_saga_orchestrator_proto_depIdxs = []int32{
	1, // 0: api.v1.orderssagaorchestrator.SagaStep.status:type_name -> api.v1.orderssagaorchestrator.SagaStepStatus
	0, // 1: api.v1.orderssagaorchestrator.OrderSaga.status:type_name -> api.v1.orderssagaorchestrator.SagaStatus
	2, // 2: api.v1.orderssagaorchestrator.OrderSaga.steps:type_name -> api.v1.orderssagaorchestrator.SagaStep
	3, // 3: api.v1.orderssagaorchestrator.GetOrderSagaResponse.saga:type_name -> api.v1.orderssagaorchestrator.OrderSaga
	4, // 4: api.v1.orderssagaorchestrator.OrdersSagaOrchestratorService.GetOrderSaga:input_type -> api.v1.orderssagaorchestrator.GetOrderSagaRequest
	5, // 5: api.v1.orderssagaorchestrator.OrdersSagaOrchestratorService.GetOrderSaga:output_type -> api.v1.orderssagaorchestrator.GetOrderSagaResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_orders_saga_orchestrator_proto_init() }
func file_orders_saga_orchestrator_proto_init() {
	if File_orders_saga_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_saga_orchestrator_proto_rawDesc), len(file_orders_saga_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_saga_orchestrator_proto_goTypes,
		DependencyIndexes: file_orders_saga_orchestrator_proto_depIdxs,
		EnumInfos:         file_orders_saga_orchestrator_proto_enumTypes,
		MessageInfos:      file_orders_saga_orchestrator_proto_msgTypes,
	}.Build()
	File_orders_saga_orchestrator_proto = out.File
	file_orders_saga_orchestrator_proto_goTypes = nil
	file_orders_saga_orchestrator_proto_depIdxs = nil
}
